pylint:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install pylint==2.0.1
    - pylint --version

  script:
    - pylint plex_schema

pytest:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install pytest==3.6.3
    - pip install pytest-cov==2.5.1
    - pytest --version

  script:
    - py.test --cov-report html --cov=plex_schema tests

  artifacts:
    paths:
      - htmlcov
    expire_in: 1h

mypy:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install mypy==0.620
    - mypy --version

  script:
    - mypy --ignore-missing-imports plex_schema

flake8:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install flake8==3.5.0
    - flake8 --version

  script:
    - flake8 plex_schema

pages:
  image: python:3.7
  stage: deploy

  dependencies:
    - pytest

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install -r requirements.docs.txt

  script:
    - sphinx-versioning build -r master docs docs/_build/html
    - mv docs/_build/html public
    - mv htmlcov public/htmlcov

  artifacts:
    paths:
      - public
    expire_in: 1h

  only:
    - tags
    - master

wheel:
  image: python:3.7
  stage: deploy

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install -U setuptools wheel

  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths:
      - dist
    expire_in: 1d

  only:
    - tags
