stages:
  - test
  - build
  - deploy

pylint:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install pylint==2.0.1
    - pylint --version

  script:
    - pylint plex_schema

pytest:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install -r requirements.txt
    - pip install pytest==3.6.3
    - pip install pytest-cov==2.5.1
    - pytest --version

  script:
    - pytest --cov-report html --cov-report term --cov=plex_schema tests

  artifacts:
    paths:
      - htmlcov
    expire_in: 1h

flake8:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install flake8==3.5.0 flake8-per-file-ignores==0.6
    - flake8 --version

  script:
    - flake8 plex_schema

pages:
  image: python:3.7
  stage: build

  dependencies:
    - pytest

  before_script:
    - python -V
    - pip install -r requirements.docs.txt

  script:
    - cd docs
    - make html
    - mv _build/html ../public
    - mv ../htmlcov ../public/htmlcov

  artifacts:
    paths:
      - public
    expire_in: 1h

  only:
    - tags
    - master

wheel:
  image: python:3.7
  stage: build

  before_script:
    - python -V
    - pip install -U setuptools wheel

  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths:
      - dist
    expire_in: 1d

  only:
    - tags

wheel:deploy:
  image: python:3.7
  stage: deploy

  dependencies:
    - wheel

  before_script:
    - python -V
    - pip install twine

  script:
    - twine upload --repository-url https://pypi.joshuaavalon.io -u $PYPI_USER -p $PYPI_TOKEN dist/*

  only:
    refs:
      - tags
    variables:
      - $PYPI_USER
      - $PYPI_TOKEN
